//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtPartMappingTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPM_ProcessFilesBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EPM_ProcessFilesBatch()
        {
            this.EPM_ProcessFilesDetail = new HashSet<EPM_ProcessFilesDetail>();
        }
    
        public int BatchId { get; set; }
        public Models.Types.ProcessFilesStages StageId { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPM_ProcessFilesDetail> EPM_ProcessFilesDetail { get; set; }
        public virtual EPM_ProcessFilesStages EPM_ProcessFilesStages { get; set; }
    }
}
