//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtPartMappingTool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Magnaflow_WebEntities : DbContext
    {
        public Magnaflow_WebEntities()
            : base("name=Magnaflow_WebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ExtPartMappingToolStagingActivity> ExtPartMappingToolStagingActivities { get; set; }
        public virtual DbSet<ExtPartMappingToolUploadStaging> ExtPartMappingToolUploadStagings { get; set; }
        public virtual DbSet<ExtPartMapping> ExtPartMappings { get; set; }
        public virtual DbSet<EPM_ProcessFilesBatch> EPM_ProcessFilesBatch { get; set; }
        public virtual DbSet<EPM_ProcessFilesDetail> EPM_ProcessFilesDetail { get; set; }
        public virtual DbSet<EPM_ProcessFilesStages> EPM_ProcessFilesStages { get; set; }
    }
}
