//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtPartMappingTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtPartMappingToolStagingActivity
    {
        public int StagingActivityId { get; set; }
        public string UserId { get; set; }
        public System.DateTime Time { get; set; }
        public Types.ActionType ActionType { get; set; }
    }
}
