//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtPartMappingTool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Magnaflow_WebEntitiesProd : DbContext
    {
        public Magnaflow_WebEntitiesProd()
            : base("name=Magnaflow_WebEntitiesProd")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ExtPartMappingToolStagingActivity> ExtPartMappingToolStagingActivities { get; set; }
        public virtual DbSet<ExtPartMappingToolUploadStaging> ExtPartMappingToolUploadStagings { get; set; }
        public virtual DbSet<ExtPartMapping> ExtPartMappings { get; set; }
    }
}
